<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
[ {"name" : "김하늘", "birth" : "1월", "address" : "충북"}, 
{"name" : "최형택", "birth" : "2월", "address" : "대전"}, 
{"name" : "김대환", "birth" : "3월", "address" : "대전"}, 
{"name" : "김명화", "birth" : "4월", "address" : "전남"}, 
{"name" : "김민제", "birth" : "5월", "address" : "대전"}, 
{"name" : "김종민", "birth" : "6월", "address" : "대전"}, 
{"name" : "김평호", "birth" : "7월", "address" : "대전"}, 
{"name" : "문준형", "birth" : "8월", "address" : "대전"}, 
{"name" : "안우영", "birth" : "9월", "address" : "대전"}, 
{"name" : "오유근", "birth" : "10월", "address" : "대전"}, 
{"name" : "윤주호", "birth" : "11월", "address" : "충북"}, 
{"name" : "이수호", "birth" : "12월", "address" : "대전"}, 
{"name" : "이은식", "birth" : "1월", "address" : "충북"}, 
{"name" : "임창현", "birth" : "2월", "address" : "충북"}, 
{"name" : "황영호", "birth" : "3월", "address" : "전남"}, 
{"name" : "강백호", "birth" : "4월", "address" : "전남"}, 
{"name" : "김백수", "birth" : "4월", "address" : "전남"},
{"name" : "강감수", "birth" : "4월", "address" : "전남"},
{"name" : "강남수", "birth" : "2월", "address" : "전남"},
{"name" : "강윤수", "birth" : "2월", "address" : "전남"},
{"name" : "김백호", "birth" : "4월", "address" : "대전"},
{"name" : "이백수", "birth" : "4월", "address" : "대전"},
{"name" : "김용민", "birth" : "6월", "address" : "대전"}, 
{"name" : "김평민", "birth" : "7월", "address" : "대전"}, 
{"name" : "문민형", "birth" : "8월", "address" : "대전"}, 
{"name" : "민우영", "birth" : "9월", "address" : "대전"}, 
{"name" : "오민근", "birth" : "10월", "address" : "대전"}, 
{"name" : "윤주민", "birth" : "11월", "address" : "충북"}, 
{"name" : "민수호", "birth" : "12월", "address" : "대전"}, 
{"name" : "이민식", "birth" : "1월", "address" : "충북"}, 
{"name" : "임민현", "birth" : "2월", "address" : "충북"} ]